
<div class="login-container">
    <h2>Bmicalculator</h2>
    <form action="<?php echo $this->getUrl('bmicalculator/product/save') ?>" method="post">
    <!-- <input type="hidden"  name="customer[customer_id]"> -->
    <div class="row">
            <input type="hidden"  name="bmi[id]">
        </div>
        <div class="form-group">
            <label for="user_name">Username:</label>
            <input type="text" id="user_name" name="bmi[user_name]" >
        </div>
        <div class="form-group">
            <label for="user_name">Weight:</label>
            <input type="float" id="text" name="bmi[weight]" >
        </div>
        <label for="Weightstatus">Weight measure:</label>
        <select name="Weightstatus" id="Weightstatus" >
            <option value="kg">kg</option>
            <option value="pounds" >pounds</option>
        </select>
      
        <div class="form-group">
            <label for="height">Height:</label>
            <input type="float" id="text" name="bmi[height]" >
        </div>
        <label for="height status">Height measure:</label>
        <select name="height status" id="height status" >
            <option value="meter">meter</option>
            <option value="feet" >feet</option>
        </select>
        <div class="form-group">
          
            <input type="hidden" id="text" name="bmi[result]" >
        </div>
        <br>
        <button type="submit">calculate</button>
        
    </form>
</div>