<div class="row border-top border-bottom">
    <?php
    $cart = $this->getQuoteItem();
    $total = 0;
    foreach ($cart as $item):
        $product = $this->getProductList()->addFieldToFilter('product_id', $item->getProductId())->getData()[0];
        // echo "<pre>";
        // print_r(get_class_methods($item));
        // die;
        ?>
        <div class="row main align-items-center">
            <form action="<?php echo Mage::getBaseUrl('sales/quote/add') ?>" method="post">
                <table>
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <pre>
                        <td><?php print_r($product->getName()); ?></td>
                        <td><?php print_r($item->getPrice()); ?></td>
                        <input type="hidden" name="sales_quote[product_id]" value="<?php echo $item->getProductId(); ?>">
                        <input type="hidden" name="sales_quote[quote_id]" value="<?php echo $item->getQuoteId(); ?>">
                        <input type="hidden" name="sales_quote[item_id]" value="<?php echo $item->getItemId(); ?>">
                        <td><input type="number" name="sales_quote[qty]" value="<?php print_r($item->getQty()); ?>" min="1"></td>
                        <td><?php print_r($item->getRowTotal()); ?></td>
                        <td>
                            <button class="button" type="submit" name="update">Update</button>
                            <a href="<?php echo Mage::getBaseUrl('sales/quote/delete'); ?>?quote_id=<?php print_r($item->getQuoteId()); ?>&item_id=<?php print_r($item->getItemId()); ?>" class="button" type="submit" name="remove">Remove</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
                  </div>
                  <?php $total += $item->getRowTotal();
    endforeach; ?>
          <div class="row main align-items-center button-container">
          <tr>
            <th>Total:</th><th><?php print_r($total); ?></th>
            <th><a href="<?php echo $this->getUrl('cart/checkout/form'); ?>" class="button" type="submit" name="checkout">checkout</a></th>
            <th><a href="<?php echo $this->getUrl('catalog/category/view'); ?>" class="button" type="submit" name="checkout">Back</a></th>
            
        
          </tr>
    </div>
      </div>