<?php
$order = $this->displayOrder();
$cancelRequests = $this->getCancelRequest();
$cancelOrderIds = [];
foreach ($cancelRequests as $cancelRequestId) {
    $cancelOrderIds[] = $cancelRequestId->getOrderId();
}
$rejectToStatus = $this->getRejectStatus();
// die;
?>
<div class="list">
    <?php foreach ($order as $_list): ?>
        <div class="order-block">
            <h2>Order Number:
                <?php echo $_list->getOrderNumber() ?>
            </h2>
            <table class="order-table">
                <thead>
                    <tr>
                        <th>Grand Total</th>
                        <th>Status</th>
                        <th>Current Status</th>
                        <th>Cancel Request</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <?php echo $_list->getGrandTotal() ?>
                        </td>
                        <td>
                            <form action="<?php echo $this->getUrl('admin/sales_customer/save') ?>" method="post">
                                <select name="order[status]" class="status-dropdown">
                                    <?php foreach ($this->getStatusMethod() as $key => $val): ?>


                                        <option value="<?php echo $key ?>" <?php echo ($_list->getStatus() === $val) ? 'selected' : ''; ?>>
                                            <?php echo $val ?>
                                        </option>

                                    <?php endforeach; ?>
                                </select>
                                <input type="text" name="order[order_id]" value="<?php echo $_list->getOrderId() ?>">
                                <input type="submit" value="Update Status" class="submit-btn">
                            </form>
                        </td>
                        <td>
                            <?php echo $_list->getStatus() ?>
                        </td>
                        <td>
                            <?php

                            if (
                                in_array($_list->getOrderId(), $cancelOrderIds) && $_list->getStatus() !== 'cancel' && $rejectToStatus !== 'cancellation declined '
                            ): ?>
                                <form action="<?php echo Mage::getBaseUrl('admin/sales_customer/approve') ?>" method="post">
                                    <input type="hidden" name="approve[order_id]" value="<?php echo $_list->getOrderId() ?>">
                                    <input type="submit" value="Approve">
                                </form>
                                <form action="<?php echo Mage::getBaseUrl('admin/sales_customer/reject') ?>" method="post">
                                    <input type="hidden" name="reject[order_id]" value="<?php echo $_list->getOrderId() ?>">
                                    <input type="submit" value="Reject">
                                </form>

                            <?php endif; ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    <?php endforeach; ?>
</div>