<header class="header">
        <div class="logo">Admin</div>
        <nav class="nav">
            <a href="<?php echo $this->getUrl('admin/catalog_product/form') ?>">Product Form</a>
            <a href="<?php echo $this->getUrl('admin/catalog_category/form') ?>">Category Form</a>
            <a href="<?php echo $this->getUrl('admin/sales_customer/list') ?>">Customer Orders</a>
            <a href="<?php echo $this->getUrl('admin/catalog_category/list') ?>">Category List</a>
            <a href="<?php echo $this->getUrl('admin/catalog_product/list') ?>">Product List</a>
            <a href="<?php echo $this->getUrl('admin/user/logout') ?>">Logout</a>
        </nav>
    </header>