<form action="<?php echo $this->getUrl('customer/account/save') ?>" method="post">
<h2>Register</h2>
         <input type="hidden"  name="customer[customer_id]">
       
    <label for="firstname">First Name:</label>
    <input type="text" id="firstname" name="customer[first_name]" required>

    <label for="lastname">Last Name:</label>
    <input type="text" id="lastname" name="customer[last_name]" required>

    <label for="email">Email:</label>
    <input type="email" id="email" name="customer[customer_email]" required>

    <label for="password">Password:</label>
    <input type="password" id="password" name="customer[password]" required>

    <button type="submit">Register</button>
</form>
</body>

</html>